services:
  guessnica-backend:
    container_name: guessnica-backend
    build:
      context: .
      dockerfile: Guessnica-backend/Dockerfile
    ports:
      - "8082:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - images:/app/wwwroot/images/locations
  db:
    image: postgres:16
    container_name: guessnica-db
    environment:
      POSTGRES_USER: guessnica
      POSTGRES_PASSWORD: guessnica
      POSTGRES_DB: guessnica
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  images: